### ISSUE TITLE
Broader Support for NIST encoded Audio Files?

### ISSUE THREAD

**Issue by j9ac9k** [TimeViewers/signalworks#23]
Issue is more of a question, should I consider submitting a PR that adds https://github.com/mcfletch/sphfile as a method of attempting to load audio files.  

In my use case, I have a NIST encoded wav file, that `soundfile` library is unable to read but `sphfile` is.   This would be an easy addition to `Wave.read_wav`, but I can incorporate this change in my library downstream and just create my Wave object via `Wave.__init__()`

**Comment by lxkain** [comment]
Since sphfile is so light, I support integration in `Wave.read_wav` directly.

**Comment by j9ac9k** [comment]
I'm going to close out this issue without implementing, turns out `sphfile` doesn't buy me anything that `soundfile` does not offer.  `sphfile` is still unable to read `shorten` encoded NIST files (well, it reads them, but has completely bogus values as a result).

`sphfile` _may_ allow for implementing a `shorten` decoder, as I'm able to read in the values of a shorten encoded file, to test if an implementation is correct (in which case they may be receptive to a PR to support shorten encoded files).

For the meantime, I'm going to close out this issue, as `soundfile` supports NIST files, but does not support `shorten` encoded files, and as far as I can tell, no python library supports that.
