### ISSUE TITLE
Wave objects are not Tracks (but they should be)

### ISSUE THREAD

**Issue by j9ac9k** [TimeViewers/signalworks#8]
* signalworks version: 0.1.2
* Python version: 3.7.3
* Operating System: macOS

### Description

Waveform, and other track-like objects are not actually tracks.  

```python
isinstance(waveformObject, Track) == False
```

currently in `wave.py` the `Wave` object is defined as such:

```python
class Wave(MetaTrack):
```

instead, it should likely be

```python
class Wave(Track, metaclass=MetaTrack):
```

**Comment by tuanad121** [comment]
Wave is now Track :D
